export const globalStylesTitle = "flex text-lg font-semibold text-gray-800"
export const globalStylesToggle = "text-[18px] font-semibold text-gray-900"
export const globalStyles_th = "px-1 py-1 text-[11px] font-semibold text-gray-200"
export const globalStyles_td = "px-1 py-1 text-[11px]"
export const globalStyles_overflow = "mt-2 w-full overflow-x-auto"
export const globalStyles_table_list = "min-w-full border border-gray-100 rounded-b-md overflow-hidden shadow-sm"