import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";
import MenuHeader from "./components/MenuHeader";
import { getServerSession } from "next-auth";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CentroInfo Engenharia e Soluções",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session: any = await getServerSession()
  return (
    <html lang="pr-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MenuHeader session={session} />
        <Sidebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
