import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";
import MenuHeader from "./components/MenuHeader";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CentroInfo Engenharia e Soluções",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
<html lang="pt-BR">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-[url('/images/bg.jpg')] bg-cover bg-center`}
  >
    <div className="absolute inset-0 bg-black/60"></div>

    <div className="relative z-10">
      <MenuHeader />
      <Sidebar />
      {children}
      <Footer />
    </div>
  </body>
</html>
  );
}
